// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// SendMessageUseCaseMock is a mock implementation of fs_watcher.SendMessageUseCase.
//
//	func TestSomethingThatUsesSendMessageUseCase(t *testing.T) {
//
//		// make and configure a mocked fs_watcher.SendMessageUseCase
//		mockedSendMessageUseCase := &SendMessageUseCaseMock{
//			SendMessageToAllFunc: func(message string)  {
//				panic("mock out the SendMessageToAll method")
//			},
//		}
//
//		// use mockedSendMessageUseCase in code that requires fs_watcher.SendMessageUseCase
//		// and then make assertions.
//
//	}
type SendMessageUseCaseMock struct {
	// SendMessageToAllFunc mocks the SendMessageToAll method.
	SendMessageToAllFunc func(message string)

	// calls tracks calls to the methods.
	calls struct {
		// SendMessageToAll holds details about calls to the SendMessageToAll method.
		SendMessageToAll []struct {
			// Message is the message argument value.
			Message string
		}
	}
	lockSendMessageToAll sync.RWMutex
}

// SendMessageToAll calls SendMessageToAllFunc.
func (mock *SendMessageUseCaseMock) SendMessageToAll(message string) {
	if mock.SendMessageToAllFunc == nil {
		panic("SendMessageUseCaseMock.SendMessageToAllFunc: method is nil but SendMessageUseCase.SendMessageToAll was just called")
	}
	callInfo := struct {
		Message string
	}{
		Message: message,
	}
	mock.lockSendMessageToAll.Lock()
	mock.calls.SendMessageToAll = append(mock.calls.SendMessageToAll, callInfo)
	mock.lockSendMessageToAll.Unlock()
	mock.SendMessageToAllFunc(message)
}

// SendMessageToAllCalls gets all the calls that were made to SendMessageToAll.
// Check the length with:
//
//	len(mockedSendMessageUseCase.SendMessageToAllCalls())
func (mock *SendMessageUseCaseMock) SendMessageToAllCalls() []struct {
	Message string
} {
	var calls []struct {
		Message string
	}
	mock.lockSendMessageToAll.RLock()
	calls = mock.calls.SendMessageToAll
	mock.lockSendMessageToAll.RUnlock()
	return calls
}
